name: Build and export binaries

on:
  push:
    branches:
      - main

jobs:
  build:

    name: Build All
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run -e esp32_1ch -e esp32_2ch -e esp32_3ch
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Binary Upload
        commit_options: '--no-verify --signoff'
        status_options: '--untracked-files=no'
        file_pattern: bin/esp32_*.bin
        push_options: --force
